version: "3"

services:
    midgard:
        build: .
        container_name: "Bifrost"
        command: npm run dev
        volumes:
            - .:/code
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "4000:4000"
    # ahab:
    #     image: ahab
    #     container_name: "Ahab"
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
